#!/bin/bash
SOURCE_BRANCH="$(git symbolic-ref -q --short HEAD)"
GIT_SHA1="$(git rev-parse -q HEAD)"

ROS_DISTRO="melodic"    # supported versions: ["melodic"]
LABEL="cpu"
VERSION=""   # supported versions: ["", "-gpu", "-gpu-ml"]
CUDA="off"
BASE="georgno/fhtw-tracker-sim:latest"
echo "[***] Build hook running"
sed -i "s/ROS_DISTRO/$ROS_DISTRO/" ./ros_entrypoint.sh

docker build \
    --rm \
    --tag fhtw-ros:"$ROS_DISTRO"_taurob_simulation_"$LABEL" \
    --build-arg ROS_DISTRO="$ROS_DISTRO" \
    --build-arg VERSION="$VERSION" \
    --build-arg CUDA="$CUDA" \
    --file Dockerfile .
sed -i "s/$ROS_DISTRO/ROS_DISTRO/" ./ros_entrypoint.sh
docker tag fhtw-ros:"$ROS_DISTRO"_taurob_simulation_"$LABEL" "$BASE-$LABEL"
docker push "$BASE-$LABEL"