map_frame: "map"          # leading "/" not allowed
robot_frame: "base_link"  # leading "/" not allowed
timeout: 20               # [s]
max_dist: 2               # [m] Maximum distance to sampe from
range_visited_node: 1     # [m] Circular range in which goals are rejected
rand_angle: 90            # [°]
max_iter: 500             # Max numbers of iterations
max_reject: 5             # Max number of goals to reject, for being to close to visited node, before executing anyways
show_marker: True         # True to visualize current goal on /visualize_marker topic
show_nodes: True         # True to visualize visited nodes